### ISSUE TITLE
Provider does not work well in lprun.exe (cmd line tool)

### ISSUE THREAD

**Issue by espenrl** [madd0/AzureStorageDriver#6]
I get an exception indicating failure in initialization code on line 171 in AzureDriver.cs. I guess the environment in lprun.exe is not the same as running under LINQPad.exe.
###### # Exception

NullReferenceException: Object reference not set to an instance of an object.
   at Madd0.AzureStorageDriver.AzureDriver.<>c__DisplayClass1.<InitializeContext>b__0(Object sender, SendingRequestEventArgs e) in d:\Projec
ts\GitHub\AzureStorageDriver\Madd0.AzureStorageDriver\AzureDriver.cs:line 171
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.Data.Services.Client.DataServiceContext.CreateRequest(Uri requestUri, String method, Boolean allowAnyType, String contentType,
Version requestVersion, Boolean sendChunked)
   at System.Data.Services.Client.DataServiceRequest.CreateResult(Object source, DataServiceContext context, AsyncCallback callback, Object
state)
   at System.Data.Services.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at System.Data.Services.Client.DataServiceQuery`1.Execute()
   at System.Data.Services.Client.DataServiceQuery`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at UserQuery in c:\Users\erl\Documents\LINQPad Queries\PSS\Tempser.linq:line 29

**Comment by madd0** [comment]
This was due to an assumption that there would always be a `SqlTranslationWriter` where the driver could write the executed request URL. The bug itself was fixed by @espenrl in ddcb18e008310565ef94604c7307edfbd4ffd7cf. The feature has since then been removed during an Azure SDK change.
